apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: oa8fzo2o6-nodejs 
  janus-idp.io/tekton: oa8fzo2o6-nodejs
  backstage.io/kubernetes-id: oa8fzo2o6-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: oa8fzo2o6-nodejs
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml