apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: oa8fzo2o6-nodejs-gitops
  description: This is GitOps manifest for oa8fzo2o6-nodejs   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-selector: rhtap/gitops=oa8fzo2o6-nodejs
    backstage.io/kubernetes-id: oa8fzo2o6-nodejs 
    backstage.io/techdocs-ref: dir:. 
    janus-idp.io/tekton: oa8fzo2o6-nodejs
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:oa8fzo2o6-nodejs
