apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: oa8fzo2o6-nodejs
  janus-idp.io/tekton: oa8fzo2o6-nodejs
  backstage.io/kubernetes-id: oa8fzo2o6-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: oa8fzo2o6-nodejs
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
